# This is a basic workflow to help you get started with Actions

name: CI #自动化名称

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths